name=Blink
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=Universal Blink library for Arduino, ESP8266, ESP32, Pico and STM32
paragraph=No need to set built-in LED pin manually. Just select board and run.
category=Signal Input/Output
architectures=*
url=https://github.com/Rafeul1997/Blink
